# -*- coding: utf-8 -*-
"""treino da ebac

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hOxQgLHcACv9bB6u5Z4GLiPpDhVD9hvk
"""

from google.colab import files

# Faça o upload do arquivo
uploaded = files.upload()

df = pd.read_csv('/content/ecommerce_estatistica.csv')

import pandas as pd
from dash import Dash, dcc, html
import plotly.express as px

# Leia o arquivo CSV que já está no Colab
df = pd.read_csv('/content/ecommerce_estatistica.csv')  # Altere o nome se necessário

# Inicializa a aplicação Dash
app = Dash(__name__)

# Gráfico de Dispersão: Relação entre Preço e Nota
scatter_fig = px.scatter(df, x='Preço', y='Nota', color='Marca', title='Relação entre Preço e Nota')

# Gráfico de Barras: Média da Nota por Marca
bar_fig = px.bar(df.groupby('Marca')['Nota'].mean().reset_index(),
                 x='Marca', y='Nota', title='Média da Nota por Marca')

# Gráfico de Pizza: Distribuição de Gênero
pie_fig = px.pie(df, names='Gênero', values='N_Avaliações', title='Distribuição de Gênero')

# Histograma: Distribuição de Desconto
hist_fig = px.histogram(df, x='Desconto', title='Distribuição de Desconto')

# Defina o layout da aplicação
app.layout = html.Div(children=[
    html.H1(children='Análise de Ecommerce'),

    html.Div(children=[
        dcc.Graph(
            id='scatter-plot',
            figure=scatter_fig
        ),
        dcc.Graph(
            id='bar-chart',
            figure=bar_fig
        ),
        dcc.Graph(
            id='pie-chart',
            figure=pie_fig
        ),
        dcc.Graph(
            id='histogram',
            figure=hist_fig
        )
    ])
])

# Execute a aplicação
if __name__ == '__main__':
    app.run(mode='inline')